name: models
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc_concurrency: ^0.2.0
  injectable: ^1.5.3
  freezed_annotation: ^1.0.0
  flutter_bloc: ^8.0.1
  repositories:
    path: ../repositories
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  build_runner: ^2.1.5
  injectable_generator: ^1.5.3

  flutter_lints: ^1.0.0