name: shared
version: 1.0.0
description: The Dart analyzer settings and best practices used internally at Google.
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.0.0
  local_auth: ^2.1.0
  loggy: ^2.0.1
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.15
  socket_io_client: ^1.0.2
  ui_kit:
    path: ../ui_kit
  uuid: ^3.0.6
  version: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

  freezed: ^1.0.0
  injectable_generator: ^1.5.2