name: services
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  cloud_firestore: ^3.1.15
  firebase_core: ^1.17.0
  uuid: ^3.0.6
  file_picker: ^5.0.1
  firebase_auth: ^3.3.18
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
