name: ui_kit
version: 1.0.0
description: The Dart analyzer settings and best practices used internally at Google.
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  dotted_border: ^2.0.0+1
  dropdown_search: ^1.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  ionicons: ^0.1.2
  popover: ^0.2.6+3
  url_launcher: ^6.0.16
